// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD88hov_qlcvSDs2hBWI7X5kCgYM4uTQhY',
    appId: '1:558642668548:web:92e1dda547b5d5fe694151',
    messagingSenderId: '558642668548',
    projectId: 'tnp-cell-85c1f',
    authDomain: 'tnp-cell-85c1f.firebaseapp.com',
    storageBucket: 'tnp-cell-85c1f.firebasestorage.app',
    measurementId: 'G-B7VF0LXM62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYG4Pjz0zf7edCECviyOMlpWGUhHm1t5M',
    appId: '1:558642668548:android:c8fe131cc6d0911a694151',
    messagingSenderId: '558642668548',
    projectId: 'tnp-cell-85c1f',
    storageBucket: 'tnp-cell-85c1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyBqeSJ5eehIAFe7UjDCrucsWOAf-kL1k',
    appId: '1:558642668548:ios:fab78897fb11863d694151',
    messagingSenderId: '558642668548',
    projectId: 'tnp-cell-85c1f',
    storageBucket: 'tnp-cell-85c1f.firebasestorage.app',
    iosBundleId: 'com.example.tnp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyBqeSJ5eehIAFe7UjDCrucsWOAf-kL1k',
    appId: '1:558642668548:ios:fab78897fb11863d694151',
    messagingSenderId: '558642668548',
    projectId: 'tnp-cell-85c1f',
    storageBucket: 'tnp-cell-85c1f.firebasestorage.app',
    iosBundleId: 'com.example.tnp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD88hov_qlcvSDs2hBWI7X5kCgYM4uTQhY',
    appId: '1:558642668548:web:29e2072f49322d5c694151',
    messagingSenderId: '558642668548',
    projectId: 'tnp-cell-85c1f',
    authDomain: 'tnp-cell-85c1f.firebaseapp.com',
    storageBucket: 'tnp-cell-85c1f.firebasestorage.app',
    measurementId: 'G-3NJQ1Y18R4',
  );
}